### ISSUE TITLE
[bug] Styles not being applied in new nextjs apps

### ISSUE THREAD

**Issue by heyitsarpit** [mirror-xyz/degen#41]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Package Version

0.0.26

### Current Behavior

Trying to render a simple `<Box />` componenet does not inject styles in the ppage. Classes on dom nodes are added but not styles are not applied.

### Expected Behavior

The components should be styled.

### Steps To Reproduce

Code  -
 
On [stackblitz](https://stackblitz.com/edit/nextjs-vhq6l4?file=pages/index.js) - does not work

On degen [Playground](https://degen-xyz.vercel.app/playroom#?code=N4Igxg9gJgpiBcIAEKkB4BCEAeSCGAzgLwA6IAFjHrAE5lIAO1UAlgHYDmpIAjAGz0ARnjABrDjQgBXNlADCEADYQa3AJ4xFygO5kAfCTapUmHI2bsuZfkJHjJM%2BUpXdBiu-UjLVZbeRYALjD0AGYQbAEAYngAtiyKatwx4RD6hsbGmFIBAeF6ABKaykgA6iqKUGgA9BjZuWwGRhnVWNiNmTU4eiAANCDaLFAB5AQIANp8ACwADAC6AL5AA) -  works

```jsx
import { Box, Button } from 'degen'

export function Header() {
  return (
    <Box as='header' padding='16' backgroundColor='yellow'>
      <Box padding='16' backgroundColor='black' color='white' fontFamily='mono'>
        <Button>Hello World</Button>
      </Box>
    </Box>
  )
}

```

**Comment by CodeAunt** [comment]
Hi, I got the same problem, no style are applied to the components. Have you fix it?

**Comment by heyitsarpit** [comment]
> Hi, I got the same problem, no style are applied to the components. Have you fix it?

@CodeAunt Yeah, I realised that I never wrapped the app with the [ThemeProvider](https://degen-xyz.vercel.app/#set-up)

**Comment by CodeAunt** [comment]
> > Hi, I got the same problem, no style are applied to the components. Have you fix it?
> 
> @CodeAunt Yeah, I realised that I never wrapped the app with the [ThemeProvider](https://degen-xyz.vercel.app/#set-up)

Sorry for not reading the document carefully. Thanks.

**Comment by CodeAunt** [comment]
> > Hi, I got the same problem, no style are applied to the components. Have you fix it?
> 
> @CodeAunt Yeah, I realised that I never wrapped the app with the [ThemeProvider](https://degen-xyz.vercel.app/#set-up)

sorry, I still fail to apply the styles.
I tried to wrap the root of the App in create-react-app like this but still fail to activate the style.
```
...
import { ThemeProvider } from 'degen';

ReactDOM.render(
  <ThemeProvider>
    <React.StrictMode>
      <Button>Click</Button>
      {/* <App /> */}
    </React.StrictMode>
  </ThemeProvider>
  ,
  document.getElementById('root')
);
...
```
And in Next.js
I tried this,
```
import { ThemeProvider, Button } from 'degen'

const MyApp = ({ Component, pageProps }: AppProps) => {
  return (
  <ThemeProvider>
    {/* <Component {...pageProps} /> */}
    <Button>Click</Button>
  </ThemeProvider>)
}
```

All of them failed.
And I also added font to them with
```
yarn add @fontsource/inter
yarn add @fontsource/ia-writer-mono
```
Could you give me some tips to make this?

**Comment by heyitsarpit** [comment]
@CodeAunt Refer to this [stackbltz example](https://stackblitz.com/edit/nextjs-vhq6l4?file=pages%2F_app.js).
In your code you seem to have missed importing the styles `import 'degen/styles';`. `ThemeProvide` is one of two imports.

**Comment by CodeAunt** [comment]
> @CodeAunt Refer to this [stackbltz example](https://stackblitz.com/edit/nextjs-vhq6l4?file=pages%2F_app.js). In your code you seem to have missed importing the styles `import 'degen/styles';`. `ThemeProvider` is one of two imports.

Oh, When I added this on react and `import 'degen/styles';` causes `can't resolve` error, I manully added the content from `style.css` to `index.css` and the components work fine now. 
And this line `import 'degen/styles';` works fine in next.js. Thanks a lot for your immediate reply ❤️
